#!/bin/bash
b=0
while :
do
/bin/sleep 0.5
a=-11
ids=''
ids=`wmctrl -l | cut -c 1-10`
d=`wmctrl -l | cut -c 1-10 | wc -c`
if [ $b -eq $d ]
then
    continue
fi
e=$[d-11]
while [ $a -lt $e ]
do
        a=$[a+11]
        #echo $a
        #echo ${ids:$a:10}
        xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id ${ids:$a:10}
        
done
b=$d
done
