#!/bin/bash
#b=0
#cd /home/han/xporp
while :
do
/bin/sleep 0.5
a=-11
b=0
c=0
ids=''
ids=`wmctrl -l | cut -c 1-10`
b=`echo $ids | wc -L`
c=$[b-10]
while [ $a -lt $c ]
do
#b=${#ids}
 
        #cat /dev/null > cmd
        #wmctrl -l | cut -c 1-10 >> /home/han/xporp/cmd
        #cat /home/han/xporp/cmd | while read line2
        a=$[a+11]
        xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id ${ids:$a:10}
done
done
